name: twitter_api_v2
description: The lightweight and powerful wrapper library for Twitter API v2.0 written in Dart language. It works cross-platform.
version: 0.0.1
repository: https://github.com/myConsciousness/twitter-api-v2

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  http: ^0.13.4
  oauth1: ^2.0.0
  json_annotation: ^4.5.0
  freezed_annotation: ^2.0.1

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
  build_runner: ^2.1.10
  json_serializable: ^6.2.0
  freezed: ^2.0.2
  import_sorter: ^4.6.0
